version: '3'

services:
  minecraft:
    image: hardmode
    ports:
      - '25565:25565'
    volumes:
      - 'dist:/data'
    environment:
      - PAPER_OUTPUT_PATH="/data/paper.jar"
      - .env
    restart: always

volumes: dist:
