version: '3'

services:
  hardmode-server:
    image: hardmode
    ports:
      - '25565:25565'
    volumes:
      - 'dist:/data'
    environment:
      ENTRYPOINT: '/data/paper.jar'
      MINECRAFT_VERSION: '1.14.4'
    restart: always

volumes:
  dist:
